### ISSUE TITLE
Feedback on MiniEX_04 by Jannik Ibsen

### ISSUE THREAD

**Issue by JannikIbsen** [PFisk/Mini-Exercises#3]
I love the idea behind this concept, if i'm not mistaken, there was meant to be more balls flying across the screen as shown in the screenshot? that would have been insanely cool. 

The way you utilize gravity in addition to the pathing being mapped onto the canvas works really well together.

Personally i would suggest changing the modifiers for the speed, the +1 modifiers does not seem to make big enough of an impact to be noticable, atleast for me.

You have made use of some very clever functions to avoid unintended interaction, such as the ellipses scaling function, though there seems to be a bug in your canvas function, if you rescale your browser window, it draws a new canvas. as illustrated here:

![balls](https://cloud.githubusercontent.com/assets/25726115/23614205/789ae2b0-0282-11e7-852c-f7eb3db7fc4e.png)

**Comment by PFisk** [comment]
Hey Jannik. More balls have been on the drawing board as well, but the main idea was to have the frame rotating and the gravity pulling downwards (is it does now). However, i couldn't get the balls to react within the frame, as it was rotating. Rotating the borders the balls collide with, would rotate the "gravity" as well, as it is mapped to the location of y.

As for the canvas rescaling bug, you are very right. I was without internet access when i finished it up, and by the time i got access, it was too late to try to fix. I crossed my fingers hoping nobody would notice, but here we are ;)
